### ISSUE TITLE
Linking a complete open-source Catalyst app into the calendar somehow...?

### ISSUE THREAD

**Issue by jmacdotorg** [perl-catalyst/2013-Advent-Staging#2]
Earlier this year I shared the source to a small but complete Catalyst-based web application, right here on GitHub: https://github.com/jmacdotorg/Spoilerific. Following some discussion on IRC over the weekend about example Catalyst apps, I mentioned my little effort, and @n0body suggested that it might make for a nice addition to this year's advent-calendar project.

So here I am! I am not sure what would be the most appropriate way to offer to link this project to the calendar. If it does seem like apt material, I'd quite appreciate some suggestions of additional work that would turn it into a good calendar addition; should I just write an article about my process, or write up some additional annotation, or is it enough just to provide the pointer with my best blessings?

**Comment by jjn1056** [comment]
Sounds great to me!  I think it would be nice to have an article where you talk about the application, what it does, and why you wrote it, and of course why you choose Catalyst.  Also anything about Catalyst that helped make the job easier or better, and anything about Catalyst that stuck out as pain points would be great.

Thanks!
John

**Comment by jmacdotorg** [comment]
OK, I'll see what I can do. May I ask for a deadline, please?

**Comment by jjn1056** [comment]
What I am saying is that Dec 15 I am no longer doing anything with Advent, and will stick my final 'Future of Catalyst?' article onto the end of whatever we have.  That being said two things:

1) the sooner I get to day 24, the sooner I go back to working on prototyping Catalyst6
2) After Dec15, even if I am hands off there's nothing stopping anyone from just adding an article, you just need an account on the Catalyst old svn server, which I am sure just asking on IRC #catalyst would get you help with.  I am not a gatekeeper or anything.  
 
and 3) people are writing and if we get to day 31, well there's no more days left ;)

Thanks

John

On Monday, December 2, 2013 10:07 AM, Jason McIntosh notifications@github.com wrote:

OK, I'll see what I can do. May I ask for a deadline, please?

**Comment by jmacdotorg** [comment]
Great -- I'll aim to have it in your hands within the next couple of weeks.

**Comment by jmacdotorg** [comment]
And lo I have submitted a pull request with a first draft in it, so I'll close this thread.
